### ISSUE TITLE
Feature: 관리자는 학기를 추가함으로써 학기별 마일리지와 세부항목을 관리할 수 있다.

### ISSUE THREAD

**Issue by zionhann** [HGU-WALAB/sw-mileage-server-kt#16]
# Acceptance Criteria (인수 기준)

Scenario: 새 학기를 추가
  Given 마일리지 카테고리와 세부 항목이 존재하고
  When 새 학기를 추가할 때
  Then 해당 학기에 사용할 마일리지와 세부항목을 관리할 수 있다.

- 학기별 마일리지 카테고리와 세부 항목을 조회할 수 있어야 함
- 글로벌 카테고리와 항목을 조회해서 선택할 수 있어야 함
- 학기별 사용할 카테고리와 세부 항목을 선택해서 추가할 수 있어야 함

# Story Points (개발 복잡도 추정)
[1, 2, 3, 5, 8]

-> 3

**Comment by yujin9747** [comment]
@zionhann 

학기별 사용할 카테고리와 세부 항목을 선택 및 선택 취소(수정) 할 수 있어야 함
선택을 취소한 항목에 이미 등록된 마일리지가 있는 경우 취소를 거부하고 관련된 마일리지 목록을 보여줘야 함

위에 두 개 마일리지 등록 한 이후에 진행하면 좋을 것 같은데 이슈 수정하고 다른 이슈로 다시 만드는건 어때요?
지금 pr 날려 놓은 것 부터 머지 하고 또 나누면 좋을 것 같아요

**Comment by zionhann** [comment]
> @zionhann
> 
> 학기별 사용할 카테고리와 세부 항목을 선택 및 선택 취소(수정) 할 수 있어야 함 선택을 취소한 항목에 이미 등록된 마일리지가 있는 경우 취소를 거부하고 관련된 마일리지 목록을 보여줘야 함
> 
> 위에 두 개 마일리지 등록 한 이후에 진행하면 좋을 것 같은데 이슈 수정하고 다른 이슈로 다시 만드는건 어때요? 지금 pr 날려 놓은 것 부터 머지 하고 또 나누면 좋을 것 같아요

네 좋아요 이슈 하나에 PR 하나를 기준으로 한다면 앞으로는 이슈를 최대한 잘게 나눠야겠어요. 리뷰할 때 코드 변화량이 많으면 리뷰가 힘드네요

**Comment by yujin9747** [comment]
> > @zionhann
> > 학기별 사용할 카테고리와 세부 항목을 선택 및 선택 취소(수정) 할 수 있어야 함 선택을 취소한 항목에 이미 등록된 마일리지가 있는 경우 취소를 거부하고 관련된 마일리지 목록을 보여줘야 함
> > 위에 두 개 마일리지 등록 한 이후에 진행하면 좋을 것 같은데 이슈 수정하고 다른 이슈로 다시 만드는건 어때요? 지금 pr 날려 놓은 것 부터 머지 하고 또 나누면 좋을 것 같아요
> 
> 네 좋아요 이슈 하나에 PR 하나를 기준으로 한다면 앞으로는 이슈를 최대한 잘게 나눠야겠어요. 리뷰할 때 코드 변화량이 많으면 리뷰가 힘드네요

좋아요
