### ISSUE TITLE
질문: 마일리지 시스템 API URI 결정

### ISSUE THREAD

**Issue by zionhann** [HGU-WALAB/sw-mileage-server-kt#26]
학생용 마일리지 시스템과 관리자용 마일리지 시스템을 URI로 어떻게 구분할까요?
제가 생각한 건 

관리자용 -> `/api/admin` 또는 `/api/manager`
학생용 -> `/api/student` 또는 `/api/public`

의견 있음 알려주세요

**Comment by yujin9747** [comment]
admin, student 로 결정
