### ISSUE TITLE
FRONT REQUEST: 필터링

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/sw-mileage-server-kt#44]
# 요구사항
필터링과 데이터 생성을 디비에 실제 가지고 있는 값들을 바탕으로 진행 하려 한다면
빌드 시점에 이 데이터들을 채워주는 작업이 필요하다.

아래의 필터링을 위한 1개의 API가 필요하다.

## 필터링 종류
학기

## 필요한 필드
pk (id) , 이름 (name)

**Comment by yujin9747** [comment]
디비에 있는 값으로 필터링 하지 않기로 함. 
api 보내지 않고 프론트에서 임의로 결정한 드롭다운 메뉴 사용.
