### ISSUE TITLE
REQUEST : [마일리지 등록] 학기별 세부 사항에 등록된 학생들 리스트 GET하는 API 필요

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/sw-mileage-server-kt#50]
## Request Desciption

사용자의 요구사항에 따라 _마일리지 등록_ 부분을 이중 테이블이 아닌 단일 테이블 + 모달 형식으로 변경한다.
이에 따라 마일리지 세부 항목 API는 기존의 것을 사용하고, 마일리지 세부항목에 등록된 학생 리스트는 클릭 이벤트 발생시 모달 속에 담아서 보여준다.
이 때 세부항목에 등록된 학생 리스트를 불러오는 API가 필요하다. 

## 예상되는 Response 형식
```

{
     [
                    {
                        "id": 15,
                        "studentName": "오인혁",
                        "studentSid": "21800446",
                        "counts": 3.0,
                        "points": null,
                        "extraPoints": 7,
                        "description1": "설명1",
                        "description2": "설명2",
                        "modDate": "2023-08-31T20:59:40"
                    },
                    {
                        "id": 17,
                        "studentName": "오인혁",
                        "studentSid": "21800446",
                        "counts": 3.0,
                        "points": null,
                        "extraPoints": 7,
                        "description1": "설명1",
                        "description2": "설명2",
                        "modDate": "2023-09-04T23:15:18"
                    }
]
}

```

**Comment by ohinhyuk** [comment]
endPoint : semester/학기/items/records

1) item에 description1 추가 부탁
2) records부분 제거

**Comment by yujin9747** [comment]
1. semesters/학기/items 엔드포인트를 사용하면 됩니다. 
2. semester/학기/items/records는 이제 안쓰고, records?semester=2023-02&semesterItem=1 로 필터링해서 보내주는 api 사용하는 걸로 할게요

**Comment by yujin9747** [comment]
<img width="586" alt="스크린샷 2023-09-07 오후 5 03 41" src="https://github.com/HGU-WALAB/sw-mileage-server-kt/assets/89755770/a57956fd-a7b7-4fd1-86e8-ea0c3bbf7a7d">

records/filter?semesterItemId=1로 요청한 결과 예시에요
