### ISSUE TITLE
Refactor: Dto 코드 스타일 변경

### ISSUE THREAD

**Issue by yujin9747** [HGU-WALAB/sw-mileage-server-kt#51]
# 기존 방식

반환 형식이 다른 api을 개발할 때마다 아래와 같이 필요한 필드만 반환하는 inner class로  InfoV1, InfoV2, InfoV3.... Dto를 생성했음. 

기존 방식의 문제점
1. V1, V2, V3.. 로 무의미한 네이밍
2. 의미를 넣어 이름을 짓자니 조합이 많아지면 이름이 길어짐
3. inner class에 따라 달라졌던 primary constructor 변수명
<img width="756" alt="스크린샷 2023-09-05 오전 10 44 02" src="https://github.com/HGU-WALAB/sw-mileage-server-kt/assets/89755770/f14a2ec2-5a8e-4a5b-964c-b0106861cdee">

타입에 따라 이름을 나누지 않을 수도 있지만 기존 방식은 그렇게 해온 상태.
4. 프론트에서 api로 데이터 받아올 때 primary constructor 변수 명도 매번 신경 써줘야 함

[ 기존 방식 예시 ]
<img width="309" alt="스크린샷 2023-09-05 오전 10 40 37" src="https://github.com/HGU-WALAB/sw-mileage-server-kt/assets/89755770/ee901c94-28c0-441d-a9df-a627c04667be">

# 새로운 방식

primary constructor 안의 변수는 list, count, description, data로 통일
리스트 조회 시 list, count, description 반환
단건 조회 시 data, description 반환

장점
1. 새로운 조합이 생길 시 새로운 inner class를 정의할 필요가 없다.
2. primary constructor로 반환되는 데이터의 이름에 규칙이 생겨 프론트에서 신경쓸 필요가 없다. 
항상 data, list, count, description으로 접근.
4. 코드의 가독성이 좋아진다.

단점
1. 조합마다 inner class를 정의하는 것이 아니기 때문에 원하는 형식을 갖췄는지 잘 확인해야 한다
2. 프론트에서 기존에 연결해 둔 api에서 primary constructor 변수명 관련 코드를 수정해야 한다. 

<img width="725" alt="스크린샷 2023-09-05 오전 10 56 55" src="https://github.com/HGU-WALAB/sw-mileage-server-kt/assets/89755770/fadb5d6e-13c4-4456-912d-50e8373e6a97">

**Comment by ohinhyuk** [comment]
통일성이 있게 되서 유지보수 측면에서 도움이 될 것 같네요!

**Comment by zionhann** [comment]
의미있는 네이밍은 환영입니다. 그런데 `description` 과 `count` 를 보내주는 게 어떤 의미인지 잘 모르겠습니다.

**Comment by yujin9747** [comment]
> 의미있는 네이밍은 환영입니다. 그런데 `description` 과 `count` 를 보내주는 게 어떤 의미인지 잘 모르겠습니다.

api가 많아지면서 헷갈리는 상황에 도움이 되겠다 싶어서 description을 넣었어요
count는 프론트에서 유용하게 쓰지 않을까 싶어서 기본으로 넣어봤어요
api 응답이 단건 조회일 때도 있고, list 반환일 때도 있는데 두 경우 반환 형식이 달라지기 때문에 두 상황을 구분하기 위해 list, data를 추가했고 그 외 필드는 api response 형식을 커스텀에서 쓰는 블로그들 보고 참고해서 만들어봤어요

https://gom20.tistory.com/117
