### ISSUE TITLE
REQUEST: [마일리지 등록] 학생 추가/수정 부분

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/sw-mileage-server-kt#65]
## Description

학생 추가 할때 학번으로 할 수 있는지가 궁금합니다.

**Comment by ohinhyuk** [comment]
그리고 post 의 api/mileage/record의 경우 이미 존재하는데 post가 간다면 수정되도록 해주세요!

**Comment by zionhann** [comment]
마일리지 등록할 때인가요 아니면 학생 추가할 때를 말씀하시는 건가요?
