### ISSUE TITLE
REQUEST: 수정일 추가

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/sw-mileage-server-kt#66]
## Description

대부분의 API들에 수정일이 포함 되어 있지 않다.
사용자의 요구 사항에 따라 수정일을 포함 시켜야 한다.

GET API 들에 수정일을 포함해서 보내주셔야 합니다.

**Comment by zionhann** [comment]
수정일 포함하도록 하겠습니다
-> 카테고리, 세부 항목, 학생 마일리지 기록에 포함시키면 될까요?
